import type { CourseItem } from "@/lib/types";

export const DEFAULT_COURSE_TEMPLATE_KEY = "class-6-8-regular-academic";

export const courseLibrary: Omit<CourseItem, "id">[] = [
  // --- SECTION: Class 6-8 ---
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    stream: "General",
    statusLabel: "In 1 Month",
    standardKey: "junior-financial-literacy-6-8",
    title: "Junior Financial Literacy (Class 6-8)",
    tagline: "Early Money Habits",
    schedule: "Weekend Workshops",
    summary: "Fun and interactive introduction to the world of money and savings.",
    description: "Teaches kids the value of money, the concept of earning, and the importance of saving through games and simulations. Sets the stage for advanced budgeting in high school.",
    duration: "3 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Class 6-8",
    courseNamesIncluded: ["Money Games", "Savings Jar Track", "Earning Basics"],
    branchesIncluded: ["Life Skills", "Finance Intro"],
    subjectsCovered: ["Barter vs Money", "Needs vs Wants", "Simple Interest"],
    points: ["Interactive simulations", "Practical piggy-bank tasks", "Decision-making games"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Month",
    standardKey: "ai-logic-foundation-6-8",
    title: "Introduction to AI & Data Logic",
    tagline: "Future Scientist Track",
    schedule: "Weekend Workshops",
    summary: "Nurturing logical thinking and data patterns for future AI excellence.",
    description: "Introduces young minds to the logic behind artificial intelligence. Focuses on pattern recognition, basic algorithms, and 'human-like' computer thinking through fun projects.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Junior Innovators",
    courseNamesIncluded: ["Pattern Logic", "Algorithm Games", "Data Discovery"],
    branchesIncluded: ["Future Tech", "Logic Building"],
    subjectsCovered: ["Logical Reasoning", "Pattern Matching", "Intro to Data"],
    points: ["Hands-on logic kits", "AI storytelling", "Certificate of foundation"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "class-6-8-regular-academic",
    title: "Class 6th-8th Regular Academic (State/CBSE)",
    tagline: "Total Academic Support",
    schedule: "Daily Evening Batches",
    summary: "Comprehensive coverage of core school subjects for State and CBSE boards.",
    description: "Expert tutoring for Mathematics, Science, and English. We focus on conceptual clarity and building a strong academic base for future board exams.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6 to 8",
    courseNamesIncluded: ["Mathematics Special", "Science Discovery", "Social Studies Focus"],
    branchesIncluded: ["Core Academics", "Concept Mastery"],
    subjectsCovered: ["Mathematics", "Physics", "Chemistry", "Biology", "English", "History", "Civics", "Geography"],
    points: ["Board-aligned syllabus", "Weekly performance tracking", "Personalized doubt solving"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    stream: "Science",
    statusLabel: "In 2 Days",
    standardKey: "class-6-8-premium-igcse-ib",
    title: "Class 6th-8th Premium Academic (ICSE/IGCSE/IB)",
    tagline: "International Standard Excellence",
    schedule: "Mon to Fri | Flexible Slots",
    summary: "Advanced curriculum support for international and high-aptitude boards.",
    description: "Specialized coaching for ICSE, IGCSE, and IB students. We focus on analytical thinking, extensive project support, and mastering complex syllabi.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6-8 International",
    courseNamesIncluded: ["Advanced Math Analysis", "Scientific Inquiry", "Literature & Global Studies"],
    branchesIncluded: ["Analytical Thinking", "International Standards"],
    subjectsCovered: ["Advanced Math", "Integrated Science", "English Literature", "World History"],
    points: ["Project guidance", "Critical thinking exercises", "In-depth subject analysis"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Month",
    standardKey: "junior-coding-robotics",
    title: "Basic Coding & Robotics (Junior)",
    tagline: "Future Tech for Kids",
    schedule: "Weekend Workshops",
    summary: "Introduction to logical thinking through block-based coding and hardware.",
    description: "Learn to build simple robots and program them. A fun way to introduce kids to the world of automation and computer logic.",
    duration: "4 Months",
    mode: "Home / Center Tutoring",
    audienceLabel: "Class 6-8",
    courseNamesIncluded: ["Block Coding Basics", "Robot Assembly", "Logic Games"],
    branchesIncluded: ["Electronics", "Programming"],
    subjectsCovered: ["Logic Gates", "Sensors", "Basic Algorithms"],
    points: ["All hardware kits provided", "Project-based learning", "Certificate of completion"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    stream: "Arts",
    statusLabel: "In 1 Week",
    standardKey: "public-speaking-comm",
    title: "Public Speaking & Communication",
    tagline: "Speak with Confidence",
    schedule: "Evening Slots",
    summary: "Empower your child to express ideas clearly and confidently.",
    description: "Overcome stage fear and improve body language. We focus on vocabulary building, speech delivery, and interactive storytelling.",
    duration: "3 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "All Levels",
    courseNamesIncluded: ["Confident Speaker Track", "Storytelling Workshop", "Debate Basics"],
    branchesIncluded: ["Soft Skills", "Personality Dev"],
    subjectsCovered: ["Vocabulary", "Body Language", "Speech Delivery"],
    points: ["Daily speaking practice", "Confidence workshops", "Video recorded assessments"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "critical-thinking-prob-solving",
    title: "Critical Thinking & Problem Solving",
    tagline: "Sharpen Your Mind",
    schedule: "Weekend Special",
    summary: "Develop advanced logic and analytical skills to solve complex puzzles.",
    description: "This course goes beyond school math to build deep reasoning abilities. Essential for future competitive exam readiness.",
    duration: "3 Months",
    mode: "Personal Tutoring",
    audienceLabel: "Class 6-10",
    courseNamesIncluded: ["Logical Reasoning Track", "Strategy Games", "Mental Math"],
    branchesIncluded: ["Cognitive Development", "Maths"],
    subjectsCovered: ["Logic", "Heuristics", "Pattern Recognition"],
    points: ["Brain teaser labs", "National level logic mocks", "Step-by-step guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    stream: "General",
    statusLabel: "In 2 Weeks",
    standardKey: "time-mgmt-study-skills",
    title: "Time Management & Study Skills",
    tagline: "Learn How to Learn",
    schedule: "Modular Workshops",
    summary: "Master the art of effective studying and time optimization.",
    description: "We teach students how to create effective study plans, manage exam stress, and use memory techniques like mind mapping.",
    duration: "2 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6-12",
    courseNamesIncluded: ["Smart Study Track", "Memory Mastery", "Goal Setting"],
    branchesIncluded: ["Academic Success", "Mindset"],
    subjectsCovered: ["Note taking", "Mind mapping", "Focus techniques"],
    points: ["Personalized study calendars", "Efficiency tracking", "Focus building exercises"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 6-8"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "pre-foundation-jee-neet-6-8",
    title: "Pre-Foundation for JEE/NEET (Class 6-8)",
    tagline: "Early Edge for Excellence",
    schedule: "Weekend Morning Batches",
    summary: "Ignite scientific curiosity and mathematical logic for future competitive success.",
    description: "Designed to build an exceptionally strong base in Mathematics and Science. We focus on Olympiad-level problems and conceptual depth that goes beyond standard school books.",
    duration: "Full Academic Year",
    mode: "Home / Center Tutoring",
    audienceLabel: "Class 6-8 Aspirants",
    courseNamesIncluded: ["Logic & Numbers", "Science Discovery Lab", "Olympiad Math"],
    branchesIncluded: ["Competitive Base", "Logical Reasoning"],
    subjectsCovered: ["Advanced Arithmetic", "Basic Algebra", "Kinematics", "Matter & Energy", "Life Processes"],
    points: ["Olympiad preparation", "Scientific temper building", "Mental ability modules"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    stream: "Science",
    statusLabel: "In 1 Month",
    standardKey: "junior-adv-science-math-6-8",
    title: "Junior Advanced Science & Mathematics",
    tagline: "Nurturing Future Scholars",
    schedule: "Evening Batches",
    summary: "Advanced curriculum for students aiming for premium academic tracks.",
    description: "A fast-paced program covering 8th and 9th standard concepts for gifted Class 6-7 students. Perfect for those looking to stay ahead of the curve.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Gifted Learners",
    courseNamesIncluded: ["Advanced Science Core", "Higher Math Intro", "Analytical Reasoning"],
    branchesIncluded: ["Accelerated Learning", "Conceptual Depth"],
    subjectsCovered: ["Physics", "Chemistry", "Biology", "Algebra", "Geometry"],
    points: ["Accelerated syllabus", "Deep conceptual mapping", "Analytical thinking labs"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Class 9-10 ---
  {
    category: "School & Junior College",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "class-9-10-regular-academic",
    title: "Class 9th-10th Regular Academic (State/CBSE)",
    tagline: "Board Toppers Program",
    schedule: "Daily Evening Batches",
    summary: "Intensive coaching for 9th and 10th standard school exams.",
    description: "Complete coverage of NCERT/State Board syllabus with focus on high-scoring strategies for Mathematics and Science.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-10",
    courseNamesIncluded: ["Mathematics Mastery", "Science Core", "Social Science Focus"],
    branchesIncluded: ["Board Exams", "Score Maximization"],
    subjectsCovered: ["Algebra", "Geometry", "Trigonometry", "Physics", "Chemistry", "Biology", "SST"],
    points: ["Detailed test series", "PYQ analysis", "Answer writing guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "In 3 Days",
    standardKey: "class-9-10-premium-igcse-ib",
    title: "Class 9th-10th Premium Academic (ICSE/IGCSE/IB)",
    tagline: "Global Academic Track",
    schedule: "Mon to Fri | Intensive",
    summary: "Specialized coaching for the rigorous international board syllabi.",
    description: "In-depth coverage of ICSE/IGCSE modules. We help students handle the high academic load with structured notes and deep concept clarity.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-10 International",
    courseNamesIncluded: ["Advanced Physics/Chem", "High-level Math", "Global Perspectives"],
    branchesIncluded: ["Global Curriculum", "Deep Analysis"],
    subjectsCovered: ["Pure Mathematics", "Organic Chemistry", "Analytical Physics", "Literature"],
    points: ["Practical support", "Mock exams for international boards", "Individual research guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Commerce",
    statusLabel: "Live",
    standardKey: "mah-cet-foundation-9-10",
    title: "MAH MBA CET Foundation (Class 9-10)",
    tagline: "Early Edge for MBA Aspirants",
    schedule: "Weekend Evening",
    summary: "Introductory track for building logical and verbal aptitude for CET.",
    description: "Focuses on abstract reasoning, logical puzzles, and advanced verbal ability. Designed for students planning to pursue management careers after graduation, starting their base in high school.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["Aptitude Basics", "Logical Puzzles", "Speed Reading"],
    branchesIncluded: ["Entrance Foundation", "Logic"],
    subjectsCovered: ["Logical Reasoning", "Abstract Reasoning", "Verbal Ability"],
    points: ["Shortcut trick training", "Daily logic puzzles", "Vocabulary building"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "upsc-civil-services-cse",
    title: "UPSC Civil Services Examination (CSE)",
    tagline: "National Level Civil Service",
    schedule: "Daily Morning & Evening",
    summary: "Comprehensive preparation for IAS, IPS, and IFS aspirants.",
    description: "In-depth coverage of General Studies (Prelims & Mains), CSAT, and Answer Writing. Our integrated approach ensures you build the conceptual depth and analytical skills required for India's most prestigious examination.",
    duration: "1-2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "UPSC Aspirants",
    courseNamesIncluded: ["GS Foundation Pro", "CSAT Mastery", "Current Affairs 365", "Answer Writing Lab"],
    branchesIncluded: ["IAS / IPS / IFS", "National Administration"],
    subjectsCovered: ["Polity", "History", "Geography", "Economy", "Ethics", "Current Affairs"],
    points: ["Daily MCQ practice", "Weekly answer evaluation", "One-on-one strategy sessions"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "mpsc-state-services-exam",
    title: "MPSC State Services Examination",
    tagline: "Maharashtra State Level Civil Service",
    schedule: "Daily Evening Batches",
    summary: "Dedicated coaching for MPSC Rajyaseva (State Services) aspirants.",
    description: "Focused preparation for Maharashtra Public Service Commission exams. Covers General Studies with special emphasis on Maharashtra's geography, history, and polity as per the latest descriptive pattern.",
    duration: "1 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "MPSC Aspirants",
    courseNamesIncluded: ["MPSC GS Core", "Maharashtra Special", "Marathi/English Grammar"],
    branchesIncluded: ["Deputy Collector", "DSP / ACP", "Class A/B Officers"],
    subjectsCovered: ["Maharashtra History", "State Polity", "Regional Geography", "GS 1-4"],
    points: ["Regional language support", "Maharashtra-focused mocks", "Mentorship from state officers"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Arts",
    statusLabel: "In 1 Month",
    standardKey: "foundation-comp-excellence-9-10",
    title: "Foundation for Competitive Excellence (Class 9-10)",
    tagline: "Success Blueprint for UPSC/MPSC",
    schedule: "Weekend Morning",
    summary: "Introductory track for students aiming for administrative services early.",
    description: "Focuses on general awareness, basic polity, geography, and historical analysis. Builds the reading habits and analytical mindset required for India's toughest civil service exams.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Future Officers",
    courseNamesIncluded: ["Civic Literacy", "World Geography Basics", "Current Affairs for Teens"],
    branchesIncluded: ["Admin Prep", "General Studies"],
    subjectsCovered: ["Polity", "Geography", "Modern History", "Aptitude"],
    points: ["Daily newspaper analysis", "Essay writing basics", "Interactive debate sessions"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "jee-neet-foundation-9-10",
    title: "JEE & NEET Foundation (Class 9-10)",
    tagline: "Strong Base for Top Entrances",
    schedule: "Daily Evening Batches",
    summary: "Comprehensive foundation for engineering and medical aspirants.",
    description: "Deep dive into Physics, Chemistry, and Mathematics/Biology. We bridge the gap between school curriculum and the rigor required for JEE/NEET.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["Advanced Science Modules", "High-level Mathematics", "Medical Bio Intro"],
    branchesIncluded: ["Entrance Foundation", "Analytical Prep"],
    subjectsCovered: ["Advanced Physics", "Inorganic Chemistry", "Calculus Basics", "Genetic Principles"],
    points: ["Concept mastery labs", "Weekly objective tests", "Direct mentor interaction"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "jee-foundation-9-10",
    title: "JEE Foundation (Class 9-10)",
    tagline: "Engineering Entrance Base",
    schedule: "Tue/Thu/Sat",
    summary: "Targeted foundation for IIT-JEE Main and Advanced.",
    description: "Focuses heavily on PCM (Physics, Chemistry, Math) with emphasis on problem-solving techniques and competitive math logic.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Engineering Aspirants",
    courseNamesIncluded: ["Math Logic Core", "Physics Problem Lab", "Chemistry Foundations"],
    branchesIncluded: ["IIT Prep", "Engineering"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics"],
    points: ["Higher secondary bridge", "Objective pattern mocks", "Formula mastery"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "neet-foundation-9-10",
    title: "NEET Foundation (Class 9-10)",
    tagline: "Medical Entrance Base",
    schedule: "Mon/Wed/Fri",
    summary: "Targeted foundation for Medical (NEET-UG) aspirants.",
    description: "Strong focus on PCB (Physics, Chemistry, Biology). We build the descriptive and objective skills needed for medical entrances.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Medical Aspirants",
    courseNamesIncluded: ["Bio Core Track", "Chem Reaction Lab", "Medical Physics"],
    branchesIncluded: ["Doctor Prep", "Biology Focus"],
    subjectsCovered: ["Physics", "Chemistry", "Biology"],
    points: ["Anatomy/Botany basics", "NCERT deep-dive", "Weekly biology quiz"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "advanced-int-science-math-9-10",
    title: "Advanced Integrated Science & Mathematics",
    tagline: "Academic Excellence Track",
    schedule: "Mon/Wed/Fri",
    summary: "Integrated approach to mastering complex science and math concepts.",
    description: "Combines 9th and 10th standard syllabi into a single, cohesive academic track. Ideal for students aiming for board merit lists and international competitions.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Merit Aspirants",
    courseNamesIncluded: ["Integrated Science Track", "Olympiad Math Prep", "Scientific Writing"],
    branchesIncluded: ["Merit Coaching", "Integrated Learning"],
    subjectsCovered: ["Mathematics", "Physics", "Chemistry", "Biology"],
    points: ["Merit-focused strategy", "Exhaustive problem sets", "Regular mock boards"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Week",
    standardKey: "advanced-coding-app-dev",
    title: "Advanced Coding & App Development",
    tagline: "Build Your Own Apps",
    schedule: "Weekend Batches",
    summary: "Transition from coding logic to building real-world applications.",
    description: "Learn Java or Python and build functional mobile or web apps. Includes database basics and UI design fundamentals.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-12",
    courseNamesIncluded: ["Java Programming", "Python for Apps", "UI/UX Basics"],
    branchesIncluded: ["Software Engineering", "Mobile Tech"],
    subjectsCovered: ["Programming Logic", "App Life Cycle", "Database Connectivity"],
    points: ["Publish your app", "Career foundation", "Coding certificate"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "ntse-scholarship-track",
    title: "NTSE & Scholarship Exam Track",
    tagline: "National Level Prep",
    schedule: "Morning Batches",
    summary: "Dedicated preparation for NTSE, MTSE, and other scholarship exams.",
    description: "Focus on Mental Ability Test (MAT) and Scholastic Aptitude Test (SAT). Shortcut techniques to crack national level recognized exams.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["MAT Training", "Science SAT Special", "Math Reasoning"],
    branchesIncluded: ["Scholarship Prep", "Aptitude Building"],
    subjectsCovered: ["Mental Ability", "Logic", "History", "Civics", "Geography", "STEM"],
    points: ["Exclusive study material", "Mock test series", "National rank tracking"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "foundation-ai-data-science-9-10",
    title: "Foundation for AI & Data Science (Class 9-10)",
    tagline: "Future-Ready Tech Skills",
    schedule: "Weekend Evening",
    summary: "Introductory course on AI and Data Science concepts for high schoolers.",
    description: "Build a strong mathematical and logical foundation for Artificial Intelligence. Covers basic statistics, logic gates, and an introduction to Python for data handling. Essential precursor to senior AI tracks.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-10",
    courseNamesIncluded: ["AI Logic Track", "Data Handling Basics", "Python Intro"],
    branchesIncluded: ["Future Tech", "Data Literacy"],
    subjectsCovered: ["Logic Gates", "Probability", "Intro to Python", "Data Interpretation"],
    points: ["Hands-on with data tools", "Logic building workshops", "Certificate of foundation"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    stream: "Commerce",
    statusLabel: "In 1 Month",
    standardKey: "financial-literacy-budgeting",
    title: "Financial Literacy & Budgeting",
    tagline: "Money Management for Teens",
    schedule: "Modular",
    summary: "Learn the basics of savings, investments, and personal finance early.",
    description: "We teach students how to manage money, understand banking, and the power of compounding. Essential life skill for future independence.",
    duration: "3 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Class 9-PG",
    courseNamesIncluded: ["Savings Track", "Intro to Markets", "Budgeting Lab"],
    branchesIncluded: ["Life Skills", "Finance"],
    subjectsCovered: ["Banking Basics", "Budgeting", "Compound Interest", "Risk Basics"],
    points: ["Simulated trading labs", "Interactive budgeting tools", "Investment basics"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    stream: "General",
    statusLabel: "In 2 Weeks",
    standardKey: "personality-dev-life-skills",
    title: "Life Skills & Personality Development",
    tagline: "Grooming for Success",
    schedule: "Weekend Intensive",
    summary: "Transform into a confident and emotionally resilient individual.",
    description: "Focus on leadership, emotional intelligence, and interpersonal skills. We help students handle social pressure and excel in group environments.",
    duration: "3 Months",
    mode: "Personal Mentoring",
    audienceLabel: "Class 9-PG",
    courseNamesIncluded: ["Leadership Module", "Emotional Intelligence", "Etiquette Track"],
    branchesIncluded: ["Holistic Growth", "Communication"],
    subjectsCovered: ["Social Values", "Resilience", "Interpersonal Communication"],
    points: ["One-on-one grooming", "Peer group workshops", "Real-world scenario labs"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Class 11-12 ---
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12"],
    stream: "Commerce",
    statusLabel: "Live",
    standardKey: "mah-mba-cet-11-12",
    title: "MAH MBA CET Intensive (Class 11-12)",
    tagline: "Direct Path to Top B-Schools",
    schedule: "Weekend Intensive Batches",
    summary: "Complete preparation for the MAH MBA CET exam for early starters.",
    description: "Deep dive into Logical Reasoning, Abstract Reasoning, Quantitative Aptitude, and Verbal Ability. Focus on speed, accuracy, and shortcut techniques used by top percentilers.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Management Aspirants",
    courseNamesIncluded: ["Logic Mastery", "Quant Speed Track", "CET Mock Series"],
    branchesIncluded: ["MBA Entrance", "Logical Analysis"],
    subjectsCovered: ["Logical Reasoning", "Abstract Reasoning", "Quant", "Verbal Ability"],
    points: ["Shortcut trick training", "Daily speed tests", "Mentorship from CET toppers"],
    audience: ["student", "educator", "admin"],
    toppers: [
      { name: "Mr. Kanade", result: "99.37 Percentile", image: "/student-photos/Mr.Kanade.png", detail: "MAH MBA CET 2024" },
      { name: "Mr. Aadesh Gaigawali", result: "99+ Percentile", image: "/student-photos/Mr.AadeshGaigawali.png", detail: "MAH MBA CET 2024" },
      { name: "Omkar Paturkar", result: "95+ Percentile", image: "/student-photos/Omkar Paturkar.png", detail: "MAH MBA CET 2024" }
    ]
  },
  {
    category: "School & Junior College",
    sections: ["Class 11-12"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "class-11-12-science-boards",
    title: "11th-12th Science Boards (HSC/CBSE/ISC/IB | PCM/PCB)",
    tagline: "Core Engineering & Medical Track",
    schedule: "Morning/Evening Shifts",
    summary: "In-depth coaching for HSC, CBSE, ISC, and IB Higher Secondary Science board exams.",
    description: "Detailed coverage of Physics, Chemistry, Biology, and Mathematics for HSC, CBSE, ISC, and IB science students. We ensure students are board-ready while maintaining high conceptual depth for both PCM and PCB pathways.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 11-12 Science",
    courseNamesIncluded: ["Physics Special", "Organic Chemistry", "Biology Core", "Advanced Math"],
    branchesIncluded: ["HSC / CBSE / ISC / IB", "Board Excellence", "Pre-Entrance Base"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics", "Biology", "English"],
    points: ["One-on-one attention", "Revision marathons", "Practical exam guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 11-12"],
    stream: "Commerce",
    statusLabel: "In 1 Week",
    standardKey: "foundation-ca-cs-cma-11-12",
    title: "Foundation for CA, CS & CMA",
    tagline: "Chartered & Professional Track",
    schedule: "Daily Evening Batches",
    summary: "Bridge the gap between school commerce and professional entrance exams.",
    description: "Integrated coaching for 11th-12th Commerce boards along with CA Foundation / CS Executive Entrance Test (CSEET) prep. Specialized focus on advanced accounting, mercantile law, and business economics.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Professional Aspirants",
    courseNamesIncluded: ["CA Foundation Core", "CS Entrance Track", "Advanced Accountancy"],
    branchesIncluded: ["Professional Commerce", "Audit & Law"],
    subjectsCovered: ["Accounting", "Business Law", "Economics", "Business Math"],
    points: ["Professional exam orientation", "Weekly board + entrance tests", "Interaction with industry pros"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 11-12"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "foundation-it-software-11-12",
    title: "IT & Software Engineering Foundation",
    tagline: "From Code to Architecture",
    schedule: "Evening / Weekend",
    summary: "Professional coding standards and system design for senior students.",
    description: "Move beyond simple programming to understand how software is actually built. Covers Git, Agile basics, and advanced data structures. Perfect foundation for professional tech degrees and industry placements.",
    duration: "5 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Future Engineers",
    courseNamesIncluded: ["System Logic", "Version Control (Git)", "Data Structures Core"],
    branchesIncluded: ["Software Foundations", "Tech Career"],
    subjectsCovered: ["Algorithms", "Data Structures", "Git/GitHub", "Software Lifecycle"],
    points: ["Build a portfolio website", "Collaborative coding projects", "Mentorship from industry devs"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12"],
    stream: "Science",
    statusLabel: "In 5 Days",
    standardKey: "jee-main-adv-intensive",
    title: "JEE Main & Advanced Preparation",
    tagline: "Target IIT/NIT",
    schedule: "Intensive Daily",
    summary: "Premium coaching for India's toughest engineering entrance.",
    description: "IIT-ian mentors guide students through high-level problem solving, conceptual depth, and speed for the actual exam.",
    duration: "1 or 2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Engg Aspirants",
    courseNamesIncluded: ["IIT Track", "Advanced Physics", "Math Problem Solving"],
    branchesIncluded: ["Entrance Readiness", "STEM"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics"],
    points: ["Personalized mentorship", "AITS series access", "Error analysis sessions"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12"],
    stream: "Science",
    statusLabel: "In 2 Days",
    standardKey: "neet-ug-intensive",
    title: "NEET-UG Medical Entrance",
    tagline: "Aim for Top Medical Colleges",
    schedule: "Daily Focus",
    summary: "Dedicated prep for MBBS/BDS entrance exams.",
    description: "In-depth Biology, Physics, and Chemistry coaching aligned with latest NEET patterns. Special emphasis on NCERT mastery.",
    duration: "1 or 2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Medical Aspirants",
    courseNamesIncluded: ["NEET Biology", "Organic Chem Special", "Physics for Medical"],
    branchesIncluded: ["Doctor Prep", "Medical Science"],
    subjectsCovered: ["Biology", "Physics", "Chemistry"],
    points: ["OMR-based tests", "NCERT finger-tip focus", "Doubt clearing labs"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 11-12", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Month",
    standardKey: "ai-ml-basics-teens",
    title: "AI & Machine Learning Basics",
    tagline: "Future-proof Your Career",
    schedule: "Weekend",
    summary: "Introduction to Artificial Intelligence and its real-world applications.",
    description: "Learn how AI works. Basic neural networks, data handling, and building simple AI models using Python. Perfect for students looking for a head start in tech.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Teens & Beginners",
    courseNamesIncluded: ["Intro to LLMs", "Python for AI", "Data Science Basics"],
    branchesIncluded: ["Advanced Tech", "Future Skills"],
    subjectsCovered: ["Machine Learning", "Data Analysis", "Python", "Automation"],
    points: ["Work with AI tools", "Portfolio building", "Tech industry insights"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Diploma ---
  {
    category: "School & Junior College",
    sections: ["Graduation", "Diploma"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "diploma-tech-electronics-elec",
    title: "Electronics & Electricals (Diploma)",
    tagline: "Vocational Excellence",
    schedule: "Evening / Weekend",
    summary: "Technical support for Diploma in Engineering (Polytechnic) students.",
    description: "Master circuit theory, electrical machines, and electronics basics. We help you clear your semester subjects and build practical skills.",
    duration: "Per Semester",
    mode: "Home / Online Tutoring",
    audienceLabel: "Diploma Students",
    courseNamesIncluded: ["Circuit Theory", "Electrical Machines", "Digital Electronics"],
    branchesIncluded: ["Technical Education", "Core Engg"],
    subjectsCovered: ["Electronics", "Power Systems", "Control Systems"],
    points: ["University syllabus focus", "Practical lab support", "Exam paper solving"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Diploma", "Skills"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "diploma-comp-hw-networking",
    title: "Computer Hardware & Networking",
    tagline: "Build IT Infrastructure",
    schedule: "Daily Labs",
    summary: "Learn to assemble, troubleshoot, and network computer systems.",
    description: "Covers A+ and N+ level hardware knowledge, IP addressing, router configuration, and system maintenance. Ideal for vocational students.",
    duration: "4 Months",
    mode: "Home / Center Tutoring",
    audienceLabel: "IT Enthusiasts",
    courseNamesIncluded: ["Hardware Lab", "Network Security Basics", "System Maintenance"],
    branchesIncluded: ["IT Infrastructure", "Vocational"],
    subjectsCovered: ["Hardware Assembly", "LAN/WAN", "Troubleshooting", "Operating Systems"],
    points: ["Hands-on with actual hardware", "Networking lab access", "Industry standard certification prep"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    stream: "Science",
    statusLabel: "In 1 Week",
    standardKey: "full-stack-mern",
    title: "Full Stack Web Dev (MERN Stack)",
    tagline: "React, Node.js, Express, MongoDB",
    schedule: "Daily Evening Bootcamps",
    summary: "Master the most popular JavaScript stack for modern web applications.",
    description: "Go from frontend basics to advanced backend architecture. Learn to build scalable applications using MongoDB for storage, Express/Node for the server, and React for the dynamic UI. Includes JWT authentication and Cloud deployment.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "IT Students & Devs",
    courseNamesIncluded: ["React Mastery", "Node.js API Dev", "Full-stack Integration"],
    branchesIncluded: ["JavaScript Eco-system", "Modern Web"],
    subjectsCovered: ["React.js", "Node.js", "MongoDB", "Express", "Redux", "Tailwind CSS"],
    points: ["Build 5 production-ready apps", "Deployment on AWS/Vercel", "Industry-standard coding practices"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "full-stack-mean-java",
    title: "Enterprise Full Stack (Java/MEAN)",
    tagline: "Angular, Spring Boot, MySQL",
    schedule: "Weekend Intensive",
    summary: "Focus on enterprise-grade applications using Java and Angular.",
    description: "Perfect for students targeting top MNCs. Covers the MEAN stack (Angular focus) and transitions into heavy backend engineering with Java Spring Boot and relational databases.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "College Students",
    courseNamesIncluded: ["Angular Core", "Spring Boot Backend", "RDBMS Specialization"],
    branchesIncluded: ["Enterprise Software", "Java Eco-system"],
    subjectsCovered: ["Angular", "Java", "Spring Boot", "MySQL", "TypeScript", "Microservices"],
    points: ["Microservices architecture", "Enterprise security protocols", "Corporate project training"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Class 11-12", "Graduation", "Skills"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "database-mastery-sql-mongodb",
    title: "Database Mastery (SQL & NoSQL)",
    tagline: "PL/SQL, MongoDB, Database Design",
    schedule: "Flexible Evening Slots",
    summary: "Become an expert in data storage and management.",
    description: "Learn the core of every software application: The Database. This course covers traditional Relational Databases (Oracle SQL, PL/SQL) and modern Document-based storage (MongoDB).",
    duration: "3 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Everyone in Tech",
    courseNamesIncluded: ["SQL & PL/SQL Pro", "MongoDB Developer", "DB Architect Track"],
    branchesIncluded: ["Data Management", "Backend Engineering"],
    subjectsCovered: ["Oracle SQL", "PL/SQL Procedures", "MongoDB Aggregation", "Database Normalization"],
    points: ["Complex query optimization", "Scaling NoSQL databases", "Real-world schema design"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    stream: "Commerce",
    statusLabel: "In 1 Month",
    standardKey: "sap-erp-essentials",
    title: "SAP ERP Essentials (FICO/MM)",
    tagline: "Enterprise Resource Planning",
    schedule: "Personalized Tutoring",
    summary: "Master the world's leading ERP system for corporate operations.",
    description: "An intensive guide to SAP modules. We specialize in FICO (Financial Accounting) and MM (Materials Management), providing hands-on training on the SAP environment used by Fortune 500 companies.",
    duration: "4 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Graduates & Working Pros",
    courseNamesIncluded: ["SAP FICO Training", "SAP MM Module", "ERP Business Flow"],
    branchesIncluded: ["Corporate Systems", "Business Process"],
    subjectsCovered: ["General Ledger", "Procurement", "Inventory Management", "Financial Reporting"],
    points: ["Hands-on with SAP Server", "Real business case studies", "Global career opportunities"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Diploma", "Skills"],
    stream: "General",
    statusLabel: "Live",
    standardKey: "resume-interview-skills",
    title: "Resume Building & Interview Skills",
    tagline: "Get Career Ready",
    schedule: "Modular",
    summary: "Master the art of job applications and successful interviews.",
    description: "We help you draft professional resumes, write cover letters, and master the behavioral aspects of corporate interviews. Includes mock simulation rounds.",
    duration: "2 Months",
    mode: "Personal Mentoring",
    audienceLabel: "Final Year Students",
    courseNamesIncluded: ["Resume Masterclass", "Soft Skills for Work", "Mock Interviews"],
    branchesIncluded: ["Career Prep", "Professional Development"],
    subjectsCovered: ["Communication", "Etiquette", "Self Branding"],
    points: ["1-on-1 resume reviews", "Live interview simulations", "LinkedIn profile setup"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Graduation ---
  {
    category: "School & Junior College",
    sections: ["Graduation"],
    stream: "Arts",
    statusLabel: "In 1 Month",
    standardKey: "undergrad-research-methodologies",
    title: "Research Methodologies (Undergraduate)",
    tagline: "Scientific Inquiry Skills",
    schedule: "Evening",
    summary: "Learn the fundamentals of academic research and data collection.",
    description: "Essential for students in Science, Arts, or Commerce looking to write theses or papers. Covers qualitative and quantitative research designs.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Degree Students",
    courseNamesIncluded: ["Research Design", "Data Analysis Basics", "Academic Writing"],
    branchesIncluded: ["Higher Academics", "Inquiry"],
    subjectsCovered: ["Hypothesis Testing", "Data Collection", "APA/MLA Styles"],
    points: ["Thesis guidance", "Scientific writing labs", "Paper publishing intro"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    stream: "Commerce",
    statusLabel: "In 2 Weeks",
    standardKey: "data-analysis-statistics-grad",
    title: "Data Analysis & Statistics",
    tagline: "Power Your Decisions",
    schedule: "Weekend",
    summary: "Master data handling using Excel, SQL, and Python.",
    description: "Go deep into statistical analysis. Ideal for commerce and science graduates looking to enter data-driven roles. Learn to interpret complex datasets.",
    duration: "5 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Degree Students",
    courseNamesIncluded: ["SQL Mastery", "Excel for Analysis", "Statistics Lab"],
    branchesIncluded: ["Data Analytics", "Business Intel"],
    subjectsCovered: ["Probablity", "Regression", "SQL Queries", "Visualization"],
    points: ["Work on real datasets", "Capstone projects", "Dashboard creation"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Week",
    standardKey: "cloud-computing-data-science-grad",
    title: "Cloud Computing & Data Science",
    tagline: "Future Tech Leadership",
    schedule: "Daily Intensive",
    summary: "Combined track for high-level software and data engineering.",
    description: "Learn to deploy models on AWS/Azure. Covers the full lifecycle from data cleaning to cloud deployment. Essential for modern software engineers.",
    duration: "8 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Tech Graduates",
    courseNamesIncluded: ["AWS Solutions Architect", "Machine Learning Track", "Cloud Ops"],
    branchesIncluded: ["Software Engineering", "Cloud Tech"],
    subjectsCovered: ["AWS/Azure", "Python", "TensorFlow", "DevOps Basics"],
    points: ["Live cloud access", "Model deployment labs", "Industry certificate"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    stream: "Commerce",
    statusLabel: "Live",
    standardKey: "digital-marketing-ecommerce",
    title: "Digital Marketing & E-Commerce",
    tagline: "Grow Brands Online",
    schedule: "Flexible Slots",
    summary: "Master SEO, SEM, and E-commerce operations.",
    description: "Learn to run ads, manage social media, and build online stores. We focus on ROI-driven marketing strategies for modern businesses.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["SEO Specialist", "Performance Marketing", "Shopify Mastery"],
    branchesIncluded: ["Digital Business", "Marketing"],
    subjectsCovered: ["SEO", "Google Ads", "Content Strategy", "Email Marketing"],
    points: ["Work on live accounts", "Google certification", "Freelancing guide"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Postgraduate (PG) ---
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    stream: "Arts",
    statusLabel: "In 1 Month",
    standardKey: "pg-advanced-research-techniques",
    title: "Advanced Research Techniques",
    tagline: "Master Your Thesis",
    schedule: "Personalized",
    summary: "Academic support for high-impact research and publication.",
    description: "Expert guidance for PG scholars. Focus on advanced statistical tools like SPSS/R, selecting research problems, and high-impact paper writing.",
    duration: "4-6 Months",
    mode: "Personal Mentoring",
    audienceLabel: "PG Students",
    courseNamesIncluded: ["R/SPSS Lab", "Journal Publication", "Grant Writing"],
    branchesIncluded: ["Academic Research", "Science"],
    subjectsCovered: ["Quantitative Analysis", "Scientific Ethics", "Publishing"],
    points: ["Journals submission help", "Plagiarism check", "Statistical tool mastery"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "big-data-analytics-pg",
    title: "Big Data & Advanced Analytics",
    tagline: "Handle Scale",
    schedule: "Intensive Evening",
    summary: "Learn to process and analyze massive datasets using modern tools.",
    description: "Covers Hadoop, Spark, and advanced Machine Learning. Essential for postgraduates looking for lead data roles in the industry.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "PG Tech Students",
    courseNamesIncluded: ["Spark/Hadoop Core", "Advanced ML", "Distributed Systems"],
    branchesIncluded: ["Data Science", "Tech"],
    subjectsCovered: ["Big Data", "Neural Networks", "Spark", "NoSQL"],
    points: ["Access to GPU clusters", "Paper implementation", "Real-world scale projects"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    stream: "Commerce",
    statusLabel: "In 1 Week",
    standardKey: "digital-transformation-ind-4",
    title: "Digital Transformation & Industry 4.0",
    tagline: "Lead the Future",
    schedule: "Weekend Masterclass",
    summary: "Understand the intersection of business and advanced tech.",
    description: "Covers IoT, Blockchain, and AI in business strategy. Ideal for MBA and PG students looking to lead digital initiatives in MNCs.",
    duration: "3 Months",
    mode: "Personal Tutoring",
    audienceLabel: "Leaders & MBAs",
    courseNamesIncluded: ["Blockchain for Business", "AI Strategy", "IoT Eco-systems"],
    branchesIncluded: ["Management", "Innovation"],
    subjectsCovered: ["Industry 4.0", "Change Management", "Digital Strategy"],
    points: ["Case studies from top MNCs", "Strategic planning labs", "Executive networking"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "teaching-pedagogical-skills",
    title: "Teaching & Pedagogical Skills",
    tagline: "Master the Art of Teaching",
    schedule: "Flexible",
    summary: "Advanced training for future professors and educators.",
    description: "Learn modern instructional design, online teaching tools, and classroom management. Essential for NET/SET aspirants and PhD scholars.",
    duration: "3 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Future Educators",
    courseNamesIncluded: ["Instructional Design", "Online Teaching Tech", "Pedagogy Core"],
    branchesIncluded: ["Education", "Professionalism"],
    subjectsCovered: ["Learning Theories", "Tech in Classroom", "Curriculum Design"],
    points: ["Live teaching practice", "Content creation labs", "Educational psychology"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Research & PhD Level ---
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    stream: "Arts",
    statusLabel: "In 1 Month",
    standardKey: "phd-academic-publishing-peer-review",
    title: "Academic Publishing & Peer Review",
    tagline: "Get Published",
    schedule: "Consultation Style",
    summary: "Navigating the world of high-impact journals and peer review processes.",
    description: "We help PhD scholars choose the right journals, handle reviewer comments, and perfect their manuscript structure for Scopus/WoS indexed publications.",
    duration: "Per Modular Consultation",
    mode: "Personal Mentoring",
    audienceLabel: "PhD Scholars",
    courseNamesIncluded: ["Journal Strategy", "Reviewer Communication", "Publication Ethics"],
    branchesIncluded: ["Research", "Publishing"],
    subjectsCovered: ["Manuscript Structuring", "Indexing", "Impact Factors"],
    points: ["Submission strategy", "Response drafting help", "Citation building"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "phd-patent-filing-ipr",
    title: "Patent Filing & Intellectual Property",
    tagline: "Protect Your Innovation",
    schedule: "Weekend Workshops",
    summary: "Legal and technical guidance for protecting your research inventions.",
    description: "Learn the basics of IPR, drafting patent applications, and navigating the filing process. Essential for researchers in engineering and applied sciences.",
    duration: "2 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Innovators",
    courseNamesIncluded: ["IPR Basics", "Patent Drafting", "Commercialization"],
    branchesIncluded: ["Innovation", "Legal"],
    subjectsCovered: ["Patent Law", "Prior Art Search", "IP Strategy"],
    points: ["Drafting support", "Search tool training", "Commercialization roadmap"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    stream: "General",
    statusLabel: "In 1 Week",
    standardKey: "phd-grant-writing-funding",
    title: "Grant Writing & Funding Acquisition",
    tagline: "Fund Your Research",
    schedule: "Modular",
    summary: "Learn to write winning proposals for national and international research grants.",
    description: "We guide you through the process of applying to DST, DBT, UGC, and international funding bodies. Focus on proposal structuring and budget planning.",
    duration: "3 Months",
    mode: "Personal Mentoring",
    audienceLabel: "PhD & Post-Docs",
    courseNamesIncluded: ["Proposal Drafting", "Budget Planning", "Impact Analysis"],
    branchesIncluded: ["Research Strategy", "Funding"],
    subjectsCovered: ["Project Proposal", "Stakeholder Management", "Funding Landscapes"],
    points: ["Review of existing proposals", "Agency-specific guidance", "Presentation prep"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "upsc-civil-services-advanced",
    title: "UPSC Civil Services (Advanced Prep)",
    tagline: "Nation's Most Prestigious",
    schedule: "Full-time",
    summary: "Comprehensive strategy for Prelims, Mains, and Interview.",
    description: "Deep GS coverage, Optional subject support, and current affairs analysis. We focus on answer writing and strategic syllabus completion.",
    duration: "12-18 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["GS Foundation", "Current Affairs", "Mains Writing"],
    branchesIncluded: ["Administration", "Govt"],
    subjectsCovered: ["History", "Polity", "Economy", "Ethics", "Geography"],
    points: ["Daily feedback", "Personalized mentorship", "Mock interview rounds"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    stream: "Commerce",
    statusLabel: "In 2 Weeks",
    standardKey: "banking-exams-ibps-sbi-po",
    title: "Banking Exams (PO & Clerk)",
    tagline: "Secure Bank Career",
    schedule: "Daily Practice",
    summary: "Speed and accuracy training for IBPS, SBI, and RBI exams.",
    description: "Master logical puzzles, fast quant calculations, and banking awareness. Regular mock tests to improve your percentile. Special focus on SBI PO and NABARD tracks.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Bank Aspirants",
    courseNamesIncluded: ["Quant Specialist", "Reasoning Puzzles", "Banking GK"],
    branchesIncluded: ["Finance", "Govt Jobs"],
    subjectsCovered: ["Maths", "Logic", "English", "Financial Awareness"],
    points: ["Speed-building mocks", "Pattern analysis", "Interview prep"],
    audience: ["student", "educator", "admin"],
    toppers: [
      { name: "Ms. Ritamvara", result: "1st Rank (SBI PO)", image: "/student-photos/Ms.  Ritamvara.png", detail: "SBI PO 2024 Success" },
      { name: "Ms. Priyanka", result: "1st Rank (SBI PO)", image: "/student-photos/Ms. Priyanka.png", detail: "SBI PO 2024 Success" },
      { name: "Ms. Darshit", result: "1st Rank (SBI PO)", image: "/student-photos/Ms.Darshit.png", detail: "SBI PO 2024 Success" },
      { name: "Mr. Ranjeet", result: "1st Rank (NABARD)", image: "/student-photos/Mr. Ranjeet.png", detail: "NABARD Excellence" }
    ]
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    stream: "General",
    statusLabel: "Live",
    standardKey: "ssc-gd-constable-prep",
    title: "SSC GD Constable Preparation",
    tagline: "Your Entry to Paramilitary",
    schedule: "Daily Physical + Theory",
    summary: "Dedicated coaching for SSC GD Constable exams.",
    description: "Comprehensive coverage of General Intelligence, Reasoning, Knowledge, and Mathematics as per the SSC GD pattern. Includes physical fitness guidance.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "SSC Aspirants",
    courseNamesIncluded: ["SSC Theory Track", "Physical Fitness Guide", "Reasoning Special"],
    branchesIncluded: ["Paramilitary Services", "Govt Jobs"],
    subjectsCovered: ["Maths", "GK", "Reasoning", "English/Hindi"],
    points: ["Regular mock tests", "Physical training tips", "PYQ solving"],
    audience: ["student", "educator", "admin"],
    toppers: [
      { name: "Mr. Vishal", result: "1st Rank (SSC GD)", image: "/student-photos/Mr.Vishal.png", detail: "SSC GD Success Story" }
    ]
  },
  {
    category: "Top Competitive Exams",
    sections: ["Graduation", "Govt Exams"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "clat-law-entrance-prep",
    title: "CLAT & Law Entrance Prep",
    tagline: "Aim for Top NLUs",
    schedule: "Daily Evening",
    summary: "Advanced coaching for CLAT, AILET, and other Law entrances.",
    description: "Intensive training on Legal Reasoning, Logical Reasoning, and Current Affairs. We help you develop the analytical mind required for top-tier law schools.",
    duration: "1 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Law Aspirants",
    courseNamesIncluded: ["Legal Aptitude Lab", "Logical Reasoning Pro", "GK Marathon"],
    branchesIncluded: ["Legal Studies", "Aptitude"],
    subjectsCovered: ["Legal Reasoning", "Logic", "English", "Current Affairs"],
    points: ["Weekly sectional mocks", "Case study analysis", "Direct mentoring from NLUs"],
    audience: ["student", "educator", "admin"],
    toppers: [
      { name: "Mr. Vaibhava", result: "1st Rank (CLAT)", image: "/student-photos/Mr.Vaibhava.png", detail: "NLU Kolkata Selection" }
    ]
  },
  {
    category: "School & Junior College",
    sections: ["Graduation"],
    stream: "Commerce",
    statusLabel: "In 1 Month",
    standardKey: "bcom-bba-professional-track",
    title: "B.Com & BBA Professional Coaching",
    tagline: "Excellence in Commerce Degree",
    schedule: "Evening Batches",
    summary: "Academic support for Mumbai University and Autonomous B.Com/BBA/BMS degrees.",
    description: "Go beyond standard degree subjects. We provide professional-level insights into Financial Accounting, Management Accounting, and Business Finance, ensuring you are industry-ready upon graduation.",
    duration: "Per Semester",
    mode: "Home / Online Tutoring",
    audienceLabel: "Commerce Graduates",
    courseNamesIncluded: ["Adv. Financial Accounting", "Taxation Special", "Corporate Finance"],
    branchesIncluded: ["Professional Commerce", "Degree Excellence"],
    subjectsCovered: ["Accounts", "Audit", "Economics", "Management"],
    points: ["Semester toppers focus", "Practical internship guidance", "Tally/GST certification support"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Primary School", "Class 6-8", "Skills"],
    stream: "General",
    statusLabel: "In 2 Weeks",
    standardKey: "mindfulness-stress-mgmt",
    title: "Mindfulness & Stress Management",
    tagline: "Focus & Emotional Balance",
    schedule: "Weekend Morning Slots",
    summary: "Techniques for concentration, emotional regulation, and stress reduction.",
    description: "Designed for students facing exam pressure. Learn deep breathing, meditation basics, and time-management strategies to stay calm and focused during academic challenges.",
    duration: "2 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Class 6-PG",
    courseNamesIncluded: ["Focus Building", "Emotional Resilience", "Zen Study Track"],
    branchesIncluded: ["Wellness", "Soft Skills"],
    subjectsCovered: ["Breathing Techniques", "Focus Exercises", "Anxiety Management"],
    points: ["Improve concentration by 40%", "Better sleep and routine", "Handling exam pressure"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Class 9-10", "Skills"],
    stream: "Science",
    statusLabel: "In 1 Week",
    standardKey: "env-conservation-sustainability",
    title: "Environmental Conservation",
    tagline: "Be a Green Leader",
    schedule: "Weekend Field Workshops",
    summary: "Practical guide to sustainability and ecological protection.",
    description: "Understand the science of climate change and learn practical ways to conserve energy, water, and reduce waste. Build a project that solves a local environmental issue.",
    duration: "3 Months",
    mode: "Home / Group Tutoring",
    audienceLabel: "Junior Students",
    courseNamesIncluded: ["Sustainability Pro", "Climate Action Track", "Eco-Project Lab"],
    branchesIncluded: ["Science", "Leadership"],
    subjectsCovered: ["Renewable Energy", "Waste Management", "Biodiversity"],
    points: ["Live eco-projects", "Field visit simulations", "Certificate of Sustainability"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Class 11-12", "Skills"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "data-vis-advanced-pg",
    title: "Advanced Data Visualization",
    tagline: "Storytelling with Data",
    schedule: "Evening Masterclass",
    summary: "Master PowerBI, Tableau, and D3.js for complex data storytelling.",
    description: "For students looking to excel in business intelligence. Learn to transform raw data into stunning interactive dashboards that drive decision-making.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Graduates & Pros",
    courseNamesIncluded: ["Tableau Mastery", "PowerBI Special", "D3.js Labs"],
    branchesIncluded: ["Business Intel", "Data Science"],
    subjectsCovered: ["Dashboard Design", "Data Storytelling", "Interactive Visuals"],
    points: ["Build 10+ Dashboards", "Corporate reporting standards", "Portfolio of visual stories"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Maharashtra State CETs ---
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12", "Entrance"],
    stream: "Science",
    statusLabel: "Live",
    standardKey: "mht-cet-pcm-pcb",
    title: "MHT-CET (Engineering & Pharmacy)",
    tagline: "Maharashtra State Entrance Excellence",
    schedule: "Daily Intensive Batches",
    summary: "Targeted coaching for MHT-CET PCM (Engineering) and PCB (Pharmacy) groups.",
    description: "Rigorous preparation for admission to B.E/B.Tech, B.Plan, B.Pharm, and Pharm.D programs in Maharashtra. Focus on State Board syllabus with entrance-level speed and accuracy.",
    duration: "1 or 2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 11-12 Science",
    courseNamesIncluded: ["MHT-CET PCM Track", "MHT-CET PCB Track", "HSC + CET Integrated"],
    branchesIncluded: ["Engineering", "Pharmacy", "Technology"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics", "Biology"],
    points: ["State Board syllabus deep-dive", "Shortcut trick training", "Chapter-wise objective tests"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Graduation", "Entrance"],
    stream: "Commerce",
    statusLabel: "Live",
    standardKey: "mah-mba-mms-mca-cet",
    title: "MAH MBA/MMS & MCA CET",
    tagline: "Postgrad Management & IT Entry",
    schedule: "Weekend & Evening Shifts",
    summary: "Master the aptitude requirements for top Maharashtra B-Schools and MCA programs.",
    description: "Dedicated training for MAH MBA/MMS-CET and MAH MCA-CET. Focus on logical reasoning, abstract reasoning, and quantitative aptitude tailored for the State Cell pattern.",
    duration: "6-8 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Graduates / Final Year",
    courseNamesIncluded: ["MBA/MMS Aptitude Pro", "MCA Logic & Comp Track", "CET Percentile Booster"],
    branchesIncluded: ["Management", "Computer Applications", "MMS"],
    subjectsCovered: ["Logical Reasoning", "Abstract Reasoning", "Quant", "Verbal", "Computer Concepts"],
    points: ["Speed-building workshops", "99+ percentile strategies", "Full-length CET mocks"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12", "Graduation", "Entrance"],
    stream: "Arts",
    statusLabel: "Live",
    standardKey: "mah-llb-3-5-years-cet",
    title: "MAH LLB CET (3 & 5 Years)",
    tagline: "Legal Career in Maharashtra",
    schedule: "Evening Batches",
    summary: "Comprehensive prep for 5-year (after 12th) and 3-year (after Graduation) Law CETs.",
    description: "Expert guidance on Legal Aptitude, Logical Reasoning, and General Knowledge as per the Maharashtra State CET Cell requirements for law admissions.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "12th / Graduates",
    courseNamesIncluded: ["Legal Aptitude Lab", "Reasoning for Law", "Current Affairs (CET Special)"],
    branchesIncluded: ["Legal Studies", "Judiciary Foundation"],
    subjectsCovered: ["Legal Aptitude", "General Knowledge", "Logical Reasoning", "English"],
    points: ["Case law analysis", "Weekly legal current affairs", "Sectional CET mocks"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Graduation", "Post Grad", "Entrance"],
    stream: "Arts",
    statusLabel: "In 1 Month",
    standardKey: "mah-b-m-ed-cet",
    title: "MAH B.Ed & M.Ed CET",
    tagline: "Teaching Excellence Foundation",
    schedule: "Weekend Special",
    summary: "Preparation for Teacher Training entrances in Maharashtra.",
    description: "Focused coaching for MAH B.Ed CET, MAH M.Ed CET, and Physical Education entrances (B.P.Ed/M.P.Ed). Includes the ELCT track for English medium colleges.",
    duration: "4 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Graduates & Pros",
    courseNamesIncluded: ["Teaching Aptitude Track", "Mental Ability for B.Ed", "ELCT Special"],
    branchesIncluded: ["Education", "Teaching Methodology"],
    subjectsCovered: ["Teaching Aptitude", "General Knowledge", "Mental Ability", "English"],
    points: ["Pedagogy intro", "ELCT preparation", "Interactive logic sessions"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12", "Entrance"],
    stream: "Arts",
    statusLabel: "In 1 Week",
    standardKey: "mah-aac-bdesign-cet",
    title: "MAH AAC & B.Design CET",
    tagline: "Arts & Design Excellence",
    schedule: "Evening Batches",
    summary: "Prep for Fine Arts, Applied Arts, and Bachelor of Design admissions.",
    description: "Specialized training for MAH AAC-CET and B.Design entrances. Covers design sensitivity, object drawing, and memory drawing requirements.",
    duration: "6 Months",
    mode: "Home / Center Tutoring",
    audienceLabel: "Class 12 Arts/Science",
    courseNamesIncluded: ["Fine Arts Lab", "Design Sensitivity Pro", "Memory Drawing"],
    branchesIncluded: ["Applied Arts", "Fine Arts", "Design"],
    subjectsCovered: ["Design Sensitivity", "General Knowledge", "Visual Logic"],
    points: ["Portfolio development", "Live sketching sessions", "Mock drawing tests"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12", "Entrance"],
    stream: "Science",
    statusLabel: "In 2 Weeks",
    standardKey: "mah-b-hmct-nursing-cet",
    title: "MAH B.HMCT & Nursing CET",
    tagline: "Hospitality & Healthcare Entry",
    schedule: "Evening Shifts",
    summary: "Dedicated prep for Hotel Management and B.Sc Nursing admissions.",
    description: "Covers the specific aptitude requirements for MAH B.HMCT CET and MH Nursing CET. Focus on service aptitude, English, and basic science components.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 12 Science",
    courseNamesIncluded: ["Hospitality Aptitude", "Nursing Foundation CET", "Service Logic"],
    branchesIncluded: ["Hotel Management", "Nursing", "Healthcare"],
    subjectsCovered: ["English", "General Awareness", "Service Aptitude", "Basic Physics/Chem/Bio"],
    points: ["Sector-specific aptitude", "Weekly mock assessments", "Career guidance sessions"],
    audience: ["student", "educator", "admin"],
  },
];

export function getCourseTemplateOptions() {
  return courseLibrary.map((course) => ({
    standardKey: course.standardKey,
    title: course.title,
  }));
}

export function getCourseTemplateByKey(standardKey: string) {
  return courseLibrary.find((course) => course.standardKey === standardKey) ?? null;
}

export function getCourseTemplateOrder(standardKey?: string) {
  if (!standardKey) {
    return Number.MAX_SAFE_INTEGER;
  }

  const index = courseLibrary.findIndex((course) => course.standardKey === standardKey);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

export function inferCourseTemplateKey(input?: string) {
  if (!input) {
    return null;
  }

  const normalized = input.trim().toLowerCase();
  
  // Create a mapping from title to standardKey
  const titleMap: Record<string, string> = {};
  courseLibrary.forEach(course => {
    titleMap[course.title.toLowerCase()] = course.standardKey;
  });

  return titleMap[normalized] ?? null;
}
