import type { CourseItem } from "@/lib/types";

export const DEFAULT_COURSE_TEMPLATE_KEY = "class-6-8-regular-academic";

export const courseLibrary: Omit<CourseItem, "id">[] = [
  // --- SECTION: Class 6-8 ---
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    statusLabel: "Live",
    standardKey: "class-6-8-regular-academic",
    title: "Class 6th-8th Regular Academic (State/CBSE)",
    tagline: "Total Academic Support",
    schedule: "Daily Evening Batches",
    summary: "Comprehensive coverage of core school subjects for State and CBSE boards.",
    description: "Expert tutoring for Mathematics, Science, and English. We focus on conceptual clarity and building a strong academic base for future board exams.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6 to 8",
    courseNamesIncluded: ["Mathematics Special", "Science Discovery", "Social Studies Focus"],
    branchesIncluded: ["Core Academics", "Concept Mastery"],
    subjectsCovered: ["Mathematics", "Physics", "Chemistry", "Biology", "English", "History", "Civics", "Geography"],
    points: ["Board-aligned syllabus", "Weekly performance tracking", "Personalized doubt solving"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    statusLabel: "In 2 Days",
    standardKey: "class-6-8-premium-igcse-ib",
    title: "Class 6th-8th Premium Academic (ICSE/IGCSE/IB)",
    tagline: "International Standard Excellence",
    schedule: "Mon to Fri | Flexible Slots",
    summary: "Advanced curriculum support for international and high-aptitude boards.",
    description: "Specialized coaching for ICSE, IGCSE, and IB students. We focus on analytical thinking, extensive project support, and mastering complex syllabi.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6-8 International",
    courseNamesIncluded: ["Advanced Math Analysis", "Scientific Inquiry", "Literature & Global Studies"],
    branchesIncluded: ["Analytical Thinking", "International Standards"],
    subjectsCovered: ["Advanced Math", "Integrated Science", "English Literature", "World History"],
    points: ["Project guidance", "Critical thinking exercises", "In-depth subject analysis"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    statusLabel: "In 1 Month",
    standardKey: "junior-coding-robotics",
    title: "Basic Coding & Robotics (Junior)",
    tagline: "Future Tech for Kids",
    schedule: "Weekend Workshops",
    summary: "Introduction to logical thinking through block-based coding and hardware.",
    description: "Learn to build simple robots and program them. A fun way to introduce kids to the world of automation and computer logic.",
    duration: "4 Months",
    mode: "Home / Center Tutoring",
    audienceLabel: "Class 6-8",
    courseNamesIncluded: ["Block Coding Basics", "Robot Assembly", "Logic Games"],
    branchesIncluded: ["Electronics", "Programming"],
    subjectsCovered: ["Logic Gates", "Sensors", "Basic Algorithms"],
    points: ["All hardware kits provided", "Project-based learning", "Certificate of completion"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    statusLabel: "In 1 Week",
    standardKey: "public-speaking-comm",
    title: "Public Speaking & Communication",
    tagline: "Speak with Confidence",
    schedule: "Evening Slots",
    summary: "Empower your child to express ideas clearly and confidently.",
    description: "Overcome stage fear and improve body language. We focus on vocabulary building, speech delivery, and interactive storytelling.",
    duration: "3 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "All Levels",
    courseNamesIncluded: ["Confident Speaker Track", "Storytelling Workshop", "Debate Basics"],
    branchesIncluded: ["Soft Skills", "Personality Dev"],
    subjectsCovered: ["Vocabulary", "Body Language", "Speech Delivery"],
    points: ["Daily speaking practice", "Confidence workshops", "Video recorded assessments"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Skills"],
    statusLabel: "Live",
    standardKey: "critical-thinking-prob-solving",
    title: "Critical Thinking & Problem Solving",
    tagline: "Sharpen Your Mind",
    schedule: "Weekend Special",
    summary: "Develop advanced logic and analytical skills to solve complex puzzles.",
    description: "This course goes beyond school math to build deep reasoning abilities. Essential for future competitive exam readiness.",
    duration: "3 Months",
    mode: "Personal Tutoring",
    audienceLabel: "Class 6-10",
    courseNamesIncluded: ["Logical Reasoning Track", "Strategy Games", "Mental Math"],
    branchesIncluded: ["Cognitive Development", "Maths"],
    subjectsCovered: ["Logic", "Heuristics", "Pattern Recognition"],
    points: ["Brain teaser labs", "National level logic mocks", "Step-by-step guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 6-8"],
    statusLabel: "In 2 Weeks",
    standardKey: "time-mgmt-study-skills",
    title: "Time Management & Study Skills",
    tagline: "Learn How to Learn",
    schedule: "Modular Workshops",
    summary: "Master the art of effective studying and time optimization.",
    description: "We teach students how to create effective study plans, manage exam stress, and use memory techniques like mind mapping.",
    duration: "2 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 6-12",
    courseNamesIncluded: ["Smart Study Track", "Memory Mastery", "Goal Setting"],
    branchesIncluded: ["Academic Success", "Mindset"],
    subjectsCovered: ["Note taking", "Mind mapping", "Focus techniques"],
    points: ["Personalized study calendars", "Efficiency tracking", "Focus building exercises"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Class 9-10 ---
  {
    category: "School & Junior College",
    sections: ["Class 9-10"],
    statusLabel: "Live",
    standardKey: "class-9-10-regular-academic",
    title: "Class 9th-10th Regular Academic (State/CBSE)",
    tagline: "Board Toppers Program",
    schedule: "Daily Evening Batches",
    summary: "Intensive coaching for 9th and 10th standard school exams.",
    description: "Complete coverage of NCERT/State Board syllabus with focus on high-scoring strategies for Mathematics and Science.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-10",
    courseNamesIncluded: ["Mathematics Mastery", "Science Core", "Social Science Focus"],
    branchesIncluded: ["Board Exams", "Score Maximization"],
    subjectsCovered: ["Algebra", "Geometry", "Trigonometry", "Physics", "Chemistry", "Biology", "SST"],
    points: ["Detailed test series", "PYQ analysis", "Answer writing guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 9-10"],
    statusLabel: "In 3 Days",
    standardKey: "class-9-10-premium-igcse-ib",
    title: "Class 9th-10th Premium Academic (ICSE/IGCSE/IB)",
    tagline: "Global Academic Track",
    schedule: "Mon to Fri | Intensive",
    summary: "Specialized coaching for the rigorous international board syllabi.",
    description: "In-depth coverage of ICSE/IGCSE modules. We help students handle the high academic load with structured notes and deep concept clarity.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-10 International",
    courseNamesIncluded: ["Advanced Physics/Chem", "High-level Math", "Global Perspectives"],
    branchesIncluded: ["Global Curriculum", "Deep Analysis"],
    subjectsCovered: ["Pure Mathematics", "Organic Chemistry", "Analytical Physics", "Literature"],
    points: ["Practical support", "Mock exams for international boards", "Individual research guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    statusLabel: "In 1 Week",
    standardKey: "advanced-coding-app-dev",
    title: "Advanced Coding & App Development",
    tagline: "Build Your Own Apps",
    schedule: "Weekend Batches",
    summary: "Transition from coding logic to building real-world applications.",
    description: "Learn Java or Python and build functional mobile or web apps. Includes database basics and UI design fundamentals.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 9-12",
    courseNamesIncluded: ["Java Programming", "Python for Apps", "UI/UX Basics"],
    branchesIncluded: ["Software Engineering", "Mobile Tech"],
    subjectsCovered: ["Programming Logic", "App Life Cycle", "Database Connectivity"],
    points: ["Publish your app", "Career foundation", "Coding certificate"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 9-10"],
    statusLabel: "Live",
    standardKey: "ntse-scholarship-track",
    title: "NTSE & Scholarship Exam Track",
    tagline: "National Level Prep",
    schedule: "Morning Batches",
    summary: "Dedicated preparation for NTSE, MTSE, and other scholarship exams.",
    description: "Focus on Mental Ability Test (MAT) and Scholastic Aptitude Test (SAT). Shortcut techniques to crack national level recognized exams.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["MAT Training", "Science SAT Special", "Math Reasoning"],
    branchesIncluded: ["Scholarship Prep", "Aptitude Building"],
    subjectsCovered: ["Mental Ability", "Logic", "History", "Civics", "Geography", "STEM"],
    points: ["Exclusive study material", "Mock test series", "National rank tracking"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    statusLabel: "In 1 Month",
    standardKey: "financial-literacy-budgeting",
    title: "Financial Literacy & Budgeting",
    tagline: "Money Management for Teens",
    schedule: "Modular",
    summary: "Learn the basics of savings, investments, and personal finance early.",
    description: "We teach students how to manage money, understand banking, and the power of compounding. Essential life skill for future independence.",
    duration: "3 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Class 9-PG",
    courseNamesIncluded: ["Savings Track", "Intro to Markets", "Budgeting Lab"],
    branchesIncluded: ["Life Skills", "Finance"],
    subjectsCovered: ["Banking Basics", "Budgeting", "Compound Interest", "Risk Basics"],
    points: ["Simulated trading labs", "Interactive budgeting tools", "Investment basics"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Skills"],
    statusLabel: "In 2 Weeks",
    standardKey: "personality-dev-life-skills",
    title: "Life Skills & Personality Development",
    tagline: "Grooming for Success",
    schedule: "Weekend Intensive",
    summary: "Transform into a confident and emotionally resilient individual.",
    description: "Focus on leadership, emotional intelligence, and interpersonal skills. We help students handle social pressure and excel in group environments.",
    duration: "3 Months",
    mode: "Personal Mentoring",
    audienceLabel: "Class 9-PG",
    courseNamesIncluded: ["Leadership Module", "Emotional Intelligence", "Etiquette Track"],
    branchesIncluded: ["Holistic Growth", "Communication"],
    subjectsCovered: ["Social Values", "Resilience", "Interpersonal Communication"],
    points: ["One-on-one grooming", "Peer group workshops", "Real-world scenario labs"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Class 11-12 ---
  {
    category: "School & Junior College",
    sections: ["Class 11-12"],
    statusLabel: "Live",
    standardKey: "class-11-12-science-boards",
    title: "11th-12th Science Boards (HSC/CBSE/ISC/IB | PCM/PCB)",
    tagline: "Core Engineering & Medical Track",
    schedule: "Morning/Evening Shifts",
    summary: "In-depth coaching for HSC, CBSE, ISC, and IB Higher Secondary Science board exams.",
    description: "Detailed coverage of Physics, Chemistry, Biology, and Mathematics for HSC, CBSE, ISC, and IB science students. We ensure students are board-ready while maintaining high conceptual depth for both PCM and PCB pathways.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 11-12 Science",
    courseNamesIncluded: ["Physics Special", "Organic Chemistry", "Biology Core", "Advanced Math"],
    branchesIncluded: ["HSC / CBSE / ISC / IB", "Board Excellence", "Pre-Entrance Base"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics", "Biology", "English"],
    points: ["One-on-one attention", "Revision marathons", "Practical exam guidance"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Class 11-12"],
    statusLabel: "In 1 Week",
    standardKey: "class-11-12-commerce-arts",
    title: "11th-12th Commerce & Arts Boards (HSC/CBSE/ISC/IB)",
    tagline: "Professional & Humanities Track",
    schedule: "Flexible Slots",
    summary: "Detailed academic support for HSC, CBSE, ISC, and IB Commerce and Arts streams.",
    description: "Expert help for Accountancy, Economics, Business Studies, and Humanities subjects across HSC, CBSE, ISC, and IB boards. Focus on clear concepts, strong writing quality, and high board percentages.",
    duration: "Full Academic Year",
    mode: "Home / Online Tutoring",
    audienceLabel: "Class 11-12 Comm/Arts",
    courseNamesIncluded: ["Accountancy Special", "Economics Mastery", "Psychology/Sociology Support"],
    branchesIncluded: ["HSC / CBSE / ISC / IB", "Professional Track", "Humanities"],
    subjectsCovered: ["Accounts", "Business Studies", "Economics", "History", "Political Science"],
    points: ["Detailed notes provided", "Paper solving focus", "Career guidance by stream"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12"],
    statusLabel: "In 5 Days",
    standardKey: "jee-main-adv-intensive",
    title: "JEE Main & Advanced Preparation",
    tagline: "Target IIT/NIT",
    schedule: "Intensive Daily",
    summary: "Premium coaching for India's toughest engineering entrance.",
    description: "IIT-ian mentors guide students through high-level problem solving, conceptual depth, and speed for the actual exam.",
    duration: "1 or 2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Engg Aspirants",
    courseNamesIncluded: ["IIT Track", "Advanced Physics", "Math Problem Solving"],
    branchesIncluded: ["Entrance Readiness", "STEM"],
    subjectsCovered: ["Physics", "Chemistry", "Mathematics"],
    points: ["Personalized mentorship", "AITS series access", "Error analysis sessions"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Competitive Exams",
    sections: ["Class 11-12"],
    statusLabel: "In 2 Days",
    standardKey: "neet-ug-intensive",
    title: "NEET-UG Medical Entrance",
    tagline: "Aim for Top Medical Colleges",
    schedule: "Daily Focus",
    summary: "Dedicated prep for MBBS/BDS entrance exams.",
    description: "In-depth Biology, Physics, and Chemistry coaching aligned with latest NEET patterns. Special emphasis on NCERT mastery.",
    duration: "1 or 2 Year Integrated",
    mode: "Home / Online Tutoring",
    audienceLabel: "Medical Aspirants",
    courseNamesIncluded: ["NEET Biology", "Organic Chem Special", "Physics for Medical"],
    branchesIncluded: ["Doctor Prep", "Medical Science"],
    subjectsCovered: ["Biology", "Physics", "Chemistry"],
    points: ["OMR-based tests", "NCERT finger-tip focus", "Doubt clearing labs"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 11-12", "Skills"],
    statusLabel: "In 1 Month",
    standardKey: "ai-ml-basics-teens",
    title: "AI & Machine Learning Basics",
    tagline: "Future-proof Your Career",
    schedule: "Weekend",
    summary: "Introduction to Artificial Intelligence and its real-world applications.",
    description: "Learn how AI works. Basic neural networks, data handling, and building simple AI models using Python. Perfect for students looking for a head start in tech.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Teens & Beginners",
    courseNamesIncluded: ["Intro to LLMs", "Python for AI", "Data Science Basics"],
    branchesIncluded: ["Advanced Tech", "Future Skills"],
    subjectsCovered: ["Machine Learning", "Data Analysis", "Python", "Automation"],
    points: ["Work with AI tools", "Portfolio building", "Tech industry insights"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Diploma ---
  {
    category: "School & Junior College",
    sections: ["Graduation", "Diploma"],
    statusLabel: "Live",
    standardKey: "diploma-tech-electronics-elec",
    title: "Electronics & Electricals (Diploma)",
    tagline: "Vocational Excellence",
    schedule: "Evening / Weekend",
    summary: "Technical support for Diploma in Engineering (Polytechnic) students.",
    description: "Master circuit theory, electrical machines, and electronics basics. We help you clear your semester subjects and build practical skills.",
    duration: "Per Semester",
    mode: "Home / Online Tutoring",
    audienceLabel: "Diploma Students",
    courseNamesIncluded: ["Circuit Theory", "Electrical Machines", "Digital Electronics"],
    branchesIncluded: ["Technical Education", "Core Engg"],
    subjectsCovered: ["Electronics", "Power Systems", "Control Systems"],
    points: ["University syllabus focus", "Practical lab support", "Exam paper solving"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Diploma", "Skills"],
    statusLabel: "In 2 Weeks",
    standardKey: "diploma-comp-hw-networking",
    title: "Computer Hardware & Networking",
    tagline: "Build IT Infrastructure",
    schedule: "Daily Labs",
    summary: "Learn to assemble, troubleshoot, and network computer systems.",
    description: "Covers A+ and N+ level hardware knowledge, IP addressing, router configuration, and system maintenance. Ideal for vocational students.",
    duration: "4 Months",
    mode: "Home / Center Tutoring",
    audienceLabel: "IT Enthusiasts",
    courseNamesIncluded: ["Hardware Lab", "Network Security Basics", "System Maintenance"],
    branchesIncluded: ["IT Infrastructure", "Vocational"],
    subjectsCovered: ["Hardware Assembly", "LAN/WAN", "Troubleshooting", "Operating Systems"],
    points: ["Hands-on with actual hardware", "Networking lab access", "Industry standard certification prep"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    statusLabel: "In 1 Week",
    standardKey: "full-stack-mern",
    title: "Full Stack Web Dev (MERN Stack)",
    tagline: "React, Node.js, Express, MongoDB",
    schedule: "Daily Evening Bootcamps",
    summary: "Master the most popular JavaScript stack for modern web applications.",
    description: "Go from frontend basics to advanced backend architecture. Learn to build scalable applications using MongoDB for storage, Express/Node for the server, and React for the dynamic UI. Includes JWT authentication and Cloud deployment.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "IT Students & Devs",
    courseNamesIncluded: ["React Mastery", "Node.js API Dev", "Full-stack Integration"],
    branchesIncluded: ["JavaScript Eco-system", "Modern Web"],
    subjectsCovered: ["React.js", "Node.js", "MongoDB", "Express", "Redux", "Tailwind CSS"],
    points: ["Build 5 production-ready apps", "Deployment on AWS/Vercel", "Industry-standard coding practices"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    statusLabel: "In 2 Weeks",
    standardKey: "full-stack-mean-java",
    title: "Enterprise Full Stack (Java/MEAN)",
    tagline: "Angular, Spring Boot, MySQL",
    schedule: "Weekend Intensive",
    summary: "Focus on enterprise-grade applications using Java and Angular.",
    description: "Perfect for students targeting top MNCs. Covers the MEAN stack (Angular focus) and transitions into heavy backend engineering with Java Spring Boot and relational databases.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "College Students",
    courseNamesIncluded: ["Angular Core", "Spring Boot Backend", "RDBMS Specialization"],
    branchesIncluded: ["Enterprise Software", "Java Eco-system"],
    subjectsCovered: ["Angular", "Java", "Spring Boot", "MySQL", "TypeScript", "Microservices"],
    points: ["Microservices architecture", "Enterprise security protocols", "Corporate project training"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Class 11-12", "Graduation", "Skills"],
    statusLabel: "Live",
    standardKey: "database-mastery-sql-mongodb",
    title: "Database Mastery (SQL & NoSQL)",
    tagline: "PL/SQL, MongoDB, Database Design",
    schedule: "Flexible Evening Slots",
    summary: "Become an expert in data storage and management.",
    description: "Learn the core of every software application: The Database. This course covers traditional Relational Databases (Oracle SQL, PL/SQL) and modern Document-based storage (MongoDB).",
    duration: "3 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Everyone in Tech",
    courseNamesIncluded: ["SQL & PL/SQL Pro", "MongoDB Developer", "DB Architect Track"],
    branchesIncluded: ["Data Management", "Backend Engineering"],
    subjectsCovered: ["Oracle SQL", "PL/SQL Procedures", "MongoDB Aggregation", "Database Normalization"],
    points: ["Complex query optimization", "Scaling NoSQL databases", "Real-world schema design"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills", "Post Grad"],
    statusLabel: "In 1 Month",
    standardKey: "sap-erp-essentials",
    title: "SAP ERP Essentials (FICO/MM)",
    tagline: "Enterprise Resource Planning",
    schedule: "Personalized Tutoring",
    summary: "Master the world's leading ERP system for corporate operations.",
    description: "An intensive guide to SAP modules. We specialize in FICO (Financial Accounting) and MM (Materials Management), providing hands-on training on the SAP environment used by Fortune 500 companies.",
    duration: "4 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Graduates & Working Pros",
    courseNamesIncluded: ["SAP FICO Training", "SAP MM Module", "ERP Business Flow"],
    branchesIncluded: ["Corporate Systems", "Business Process"],
    subjectsCovered: ["General Ledger", "Procurement", "Inventory Management", "Financial Reporting"],
    points: ["Hands-on with SAP Server", "Real business case studies", "Global career opportunities"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Diploma", "Skills"],
    statusLabel: "Live",
    standardKey: "resume-interview-skills",
    title: "Resume Building & Interview Skills",
    tagline: "Get Career Ready",
    schedule: "Modular",
    summary: "Master the art of job applications and successful interviews.",
    description: "We help you draft professional resumes, write cover letters, and master the behavioral aspects of corporate interviews. Includes mock simulation rounds.",
    duration: "2 Months",
    mode: "Personal Mentoring",
    audienceLabel: "Final Year Students",
    courseNamesIncluded: ["Resume Masterclass", "Soft Skills for Work", "Mock Interviews"],
    branchesIncluded: ["Career Prep", "Professional Development"],
    subjectsCovered: ["Communication", "Etiquette", "Self Branding"],
    points: ["1-on-1 resume reviews", "Live interview simulations", "LinkedIn profile setup"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Graduation ---
  {
    category: "School & Junior College",
    sections: ["Graduation"],
    statusLabel: "In 1 Month",
    standardKey: "undergrad-research-methodologies",
    title: "Research Methodologies (Undergraduate)",
    tagline: "Scientific Inquiry Skills",
    schedule: "Evening",
    summary: "Learn the fundamentals of academic research and data collection.",
    description: "Essential for students in Science, Arts, or Commerce looking to write theses or papers. Covers qualitative and quantitative research designs.",
    duration: "4 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Degree Students",
    courseNamesIncluded: ["Research Design", "Data Analysis Basics", "Academic Writing"],
    branchesIncluded: ["Higher Academics", "Inquiry"],
    subjectsCovered: ["Hypothesis Testing", "Data Collection", "APA/MLA Styles"],
    points: ["Thesis guidance", "Scientific writing labs", "Paper publishing intro"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    statusLabel: "In 2 Weeks",
    standardKey: "data-analysis-statistics-grad",
    title: "Data Analysis & Statistics",
    tagline: "Power Your Decisions",
    schedule: "Weekend",
    summary: "Master data handling using Excel, SQL, and Python.",
    description: "Go deep into statistical analysis. Ideal for commerce and science graduates looking to enter data-driven roles. Learn to interpret complex datasets.",
    duration: "5 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Degree Students",
    courseNamesIncluded: ["SQL Mastery", "Excel for Analysis", "Statistics Lab"],
    branchesIncluded: ["Data Analytics", "Business Intel"],
    subjectsCovered: ["Probablity", "Regression", "SQL Queries", "Visualization"],
    points: ["Work on real datasets", "Capstone projects", "Dashboard creation"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    statusLabel: "In 1 Week",
    standardKey: "cloud-computing-data-science-grad",
    title: "Cloud Computing & Data Science",
    tagline: "Future Tech Leadership",
    schedule: "Daily Intensive",
    summary: "Combined track for high-level software and data engineering.",
    description: "Learn to deploy models on AWS/Azure. Covers the full lifecycle from data cleaning to cloud deployment. Essential for modern software engineers.",
    duration: "8 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Tech Graduates",
    courseNamesIncluded: ["AWS Solutions Architect", "Machine Learning Track", "Cloud Ops"],
    branchesIncluded: ["Software Engineering", "Cloud Tech"],
    subjectsCovered: ["AWS/Azure", "Python", "TensorFlow", "DevOps Basics"],
    points: ["Live cloud access", "Model deployment labs", "Industry certificate"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Graduation", "Skills"],
    statusLabel: "Live",
    standardKey: "digital-marketing-ecommerce",
    title: "Digital Marketing & E-Commerce",
    tagline: "Grow Brands Online",
    schedule: "Flexible Slots",
    summary: "Master SEO, SEM, and E-commerce operations.",
    description: "Learn to run ads, manage social media, and build online stores. We focus on ROI-driven marketing strategies for modern businesses.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["SEO Specialist", "Performance Marketing", "Shopify Mastery"],
    branchesIncluded: ["Digital Business", "Marketing"],
    subjectsCovered: ["SEO", "Google Ads", "Content Strategy", "Email Marketing"],
    points: ["Work on live accounts", "Google certification", "Freelancing guide"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Postgraduate (PG) ---
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    statusLabel: "In 1 Month",
    standardKey: "pg-advanced-research-techniques",
    title: "Advanced Research Techniques",
    tagline: "Master Your Thesis",
    schedule: "Personalized",
    summary: "Academic support for high-impact research and publication.",
    description: "Expert guidance for PG scholars. Focus on advanced statistical tools like SPSS/R, selecting research problems, and high-impact paper writing.",
    duration: "4-6 Months",
    mode: "Personal Mentoring",
    audienceLabel: "PG Students",
    courseNamesIncluded: ["R/SPSS Lab", "Journal Publication", "Grant Writing"],
    branchesIncluded: ["Academic Research", "Science"],
    subjectsCovered: ["Quantitative Analysis", "Scientific Ethics", "Publishing"],
    points: ["Journals submission help", "Plagiarism check", "Statistical tool mastery"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    statusLabel: "In 2 Weeks",
    standardKey: "big-data-analytics-pg",
    title: "Big Data & Advanced Analytics",
    tagline: "Handle Scale",
    schedule: "Intensive Evening",
    summary: "Learn to process and analyze massive datasets using modern tools.",
    description: "Covers Hadoop, Spark, and advanced Machine Learning. Essential for postgraduates looking for lead data roles in the industry.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "PG Tech Students",
    courseNamesIncluded: ["Spark/Hadoop Core", "Advanced ML", "Distributed Systems"],
    branchesIncluded: ["Data Science", "Tech"],
    subjectsCovered: ["Big Data", "Neural Networks", "Spark", "NoSQL"],
    points: ["Access to GPU clusters", "Paper implementation", "Real-world scale projects"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    statusLabel: "In 1 Week",
    standardKey: "digital-transformation-ind-4",
    title: "Digital Transformation & Industry 4.0",
    tagline: "Lead the Future",
    schedule: "Weekend Masterclass",
    summary: "Understand the intersection of business and advanced tech.",
    description: "Covers IoT, Blockchain, and AI in business strategy. Ideal for MBA and PG students looking to lead digital initiatives in MNCs.",
    duration: "3 Months",
    mode: "Personal Tutoring",
    audienceLabel: "Leaders & MBAs",
    courseNamesIncluded: ["Blockchain for Business", "AI Strategy", "IoT Eco-systems"],
    branchesIncluded: ["Management", "Innovation"],
    subjectsCovered: ["Industry 4.0", "Change Management", "Digital Strategy"],
    points: ["Case studies from top MNCs", "Strategic planning labs", "Executive networking"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Post Grad", "Skills"],
    statusLabel: "Live",
    standardKey: "teaching-pedagogical-skills",
    title: "Teaching & Pedagogical Skills",
    tagline: "Master the Art of Teaching",
    schedule: "Flexible",
    summary: "Advanced training for future professors and educators.",
    description: "Learn modern instructional design, online teaching tools, and classroom management. Essential for NET/SET aspirants and PhD scholars.",
    duration: "3 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Future Educators",
    courseNamesIncluded: ["Instructional Design", "Online Teaching Tech", "Pedagogy Core"],
    branchesIncluded: ["Education", "Professionalism"],
    subjectsCovered: ["Learning Theories", "Tech in Classroom", "Curriculum Design"],
    points: ["Live teaching practice", "Content creation labs", "Educational psychology"],
    audience: ["student", "educator", "admin"],
  },

  // --- SECTION: Research & PhD Level ---
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    statusLabel: "In 1 Month",
    standardKey: "phd-academic-publishing-peer-review",
    title: "Academic Publishing & Peer Review",
    tagline: "Get Published",
    schedule: "Consultation Style",
    summary: "Navigating the world of high-impact journals and peer review processes.",
    description: "We help PhD scholars choose the right journals, handle reviewer comments, and perfect their manuscript structure for Scopus/WoS indexed publications.",
    duration: "Per Modular Consultation",
    mode: "Personal Mentoring",
    audienceLabel: "PhD Scholars",
    courseNamesIncluded: ["Journal Strategy", "Reviewer Communication", "Publication Ethics"],
    branchesIncluded: ["Research", "Publishing"],
    subjectsCovered: ["Manuscript Structuring", "Indexing", "Impact Factors"],
    points: ["Submission strategy", "Response drafting help", "Citation building"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    statusLabel: "In 2 Weeks",
    standardKey: "phd-patent-filing-ipr",
    title: "Patent Filing & Intellectual Property",
    tagline: "Protect Your Innovation",
    schedule: "Weekend Workshops",
    summary: "Legal and technical guidance for protecting your research inventions.",
    description: "Learn the basics of IPR, drafting patent applications, and navigating the filing process. Essential for researchers in engineering and applied sciences.",
    duration: "2 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Innovators",
    courseNamesIncluded: ["IPR Basics", "Patent Drafting", "Commercialization"],
    branchesIncluded: ["Innovation", "Legal"],
    subjectsCovered: ["Patent Law", "Prior Art Search", "IP Strategy"],
    points: ["Drafting support", "Search tool training", "Commercialization roadmap"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "School & Junior College",
    sections: ["Post Grad"],
    statusLabel: "In 1 Week",
    standardKey: "phd-grant-writing-funding",
    title: "Grant Writing & Funding Acquisition",
    tagline: "Fund Your Research",
    schedule: "Modular",
    summary: "Learn to write winning proposals for national and international research grants.",
    description: "We guide you through the process of applying to DST, DBT, UGC, and international funding bodies. Focus on proposal structuring and budget planning.",
    duration: "3 Months",
    mode: "Personal Mentoring",
    audienceLabel: "PhD & Post-Docs",
    courseNamesIncluded: ["Proposal Drafting", "Budget Planning", "Impact Analysis"],
    branchesIncluded: ["Research Strategy", "Funding"],
    subjectsCovered: ["Project Proposal", "Stakeholder Management", "Funding Landscapes"],
    points: ["Review of existing proposals", "Agency-specific guidance", "Presentation prep"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    statusLabel: "Live",
    standardKey: "upsc-civil-services-advanced",
    title: "UPSC Civil Services (Advanced Prep)",
    tagline: "Nation's Most Prestigious",
    schedule: "Full-time",
    summary: "Comprehensive strategy for Prelims, Mains, and Interview.",
    description: "Deep GS coverage, Optional subject support, and current affairs analysis. We focus on answer writing and strategic syllabus completion.",
    duration: "12-18 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Aspirants",
    courseNamesIncluded: ["GS Foundation", "Current Affairs", "Mains Writing"],
    branchesIncluded: ["Administration", "Govt"],
    subjectsCovered: ["History", "Polity", "Economy", "Ethics", "Geography"],
    points: ["Daily feedback", "Personalized mentorship", "Mock interview rounds"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Government Exams",
    sections: ["Govt Exams"],
    statusLabel: "In 2 Weeks",
    standardKey: "banking-exams-ibps-sbi-po",
    title: "Banking Exams (PO & Clerk)",
    tagline: "Secure Bank Career",
    schedule: "Daily Practice",
    summary: "Speed and accuracy training for IBPS, SBI, and RBI exams.",
    description: "Master logical puzzles, fast quant calculations, and banking awareness. Regular mock tests to improve your percentile.",
    duration: "6 Months",
    mode: "Home / Online Tutoring",
    audienceLabel: "Bank Aspirants",
    courseNamesIncluded: ["Quant Specialist", "Reasoning Puzzles", "Banking GK"],
    branchesIncluded: ["Finance", "Govt Jobs"],
    subjectsCovered: ["Maths", "Logic", "English", "Financial Awareness"],
    points: ["Speed-building mocks", "Pattern analysis", "Interview prep"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Primary School", "Class 6-8", "Skills"],
    statusLabel: "In 2 Weeks",
    standardKey: "mindfulness-stress-mgmt",
    title: "Mindfulness & Stress Management",
    tagline: "Focus & Emotional Balance",
    schedule: "Weekend Morning Slots",
    summary: "Techniques for concentration, emotional regulation, and stress reduction.",
    description: "Designed for students facing exam pressure. Learn deep breathing, meditation basics, and time-management strategies to stay calm and focused during academic challenges.",
    duration: "2 Months",
    mode: "Online / Personal Tutoring",
    audienceLabel: "Class 6-PG",
    courseNamesIncluded: ["Focus Building", "Emotional Resilience", "Zen Study Track"],
    branchesIncluded: ["Wellness", "Soft Skills"],
    subjectsCovered: ["Breathing Techniques", "Focus Exercises", "Anxiety Management"],
    points: ["Improve concentration by 40%", "Better sleep and routine", "Handling exam pressure"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 6-8", "Class 9-10", "Skills"],
    statusLabel: "In 1 Week",
    standardKey: "env-conservation-sustainability",
    title: "Environmental Conservation",
    tagline: "Be a Green Leader",
    schedule: "Weekend Field Workshops",
    summary: "Practical guide to sustainability and ecological protection.",
    description: "Understand the science of climate change and learn practical ways to conserve energy, water, and reduce waste. Build a project that solves a local environmental issue.",
    duration: "3 Months",
    mode: "Home / Group Tutoring",
    audienceLabel: "Junior Students",
    courseNamesIncluded: ["Sustainability Pro", "Climate Action Track", "Eco-Project Lab"],
    branchesIncluded: ["Science", "Leadership"],
    subjectsCovered: ["Renewable Energy", "Waste Management", "Biodiversity"],
    points: ["Live eco-projects", "Field visit simulations", "Certificate of Sustainability"],
    audience: ["student", "educator", "admin"],
  },
  {
    category: "Top Digital & Future Skills",
    sections: ["Class 9-10", "Class 11-12", "Skills"],
    statusLabel: "Live",
    standardKey: "data-vis-advanced-pg",
    title: "Advanced Data Visualization",
    tagline: "Storytelling with Data",
    schedule: "Evening Masterclass",
    summary: "Master PowerBI, Tableau, and D3.js for complex data storytelling.",
    description: "For students looking to excel in business intelligence. Learn to transform raw data into stunning interactive dashboards that drive decision-making.",
    duration: "4 Months",
    mode: "Online / Home Tutoring",
    audienceLabel: "Graduates & Pros",
    courseNamesIncluded: ["Tableau Mastery", "PowerBI Special", "D3.js Labs"],
    branchesIncluded: ["Business Intel", "Data Science"],
    subjectsCovered: ["Dashboard Design", "Data Storytelling", "Interactive Visuals"],
    points: ["Build 10+ Dashboards", "Corporate reporting standards", "Portfolio of visual stories"],
    audience: ["student", "educator", "admin"],
  },
];

export function getCourseTemplateOptions() {
  return courseLibrary.map((course) => ({
    standardKey: course.standardKey,
    title: course.title,
  }));
}

export function getCourseTemplateByKey(standardKey: string) {
  return courseLibrary.find((course) => course.standardKey === standardKey) ?? null;
}

export function getCourseTemplateOrder(standardKey?: string) {
  if (!standardKey) {
    return Number.MAX_SAFE_INTEGER;
  }

  const index = courseLibrary.findIndex((course) => course.standardKey === standardKey);
  return index === -1 ? Number.MAX_SAFE_INTEGER : index;
}

export function inferCourseTemplateKey(input?: string) {
  if (!input) {
    return null;
  }

  const normalized = input.trim().toLowerCase();
  
  // Create a mapping from title to standardKey
  const titleMap: Record<string, string> = {};
  courseLibrary.forEach(course => {
    titleMap[course.title.toLowerCase()] = course.standardKey;
  });

  return titleMap[normalized] ?? null;
}
